const CLIENT_ID='YOUR_GOOGLE_OAUTH_CLIENT_ID.apps.googleusercontent.com';
const SCOPES='https://www.googleapis.com/auth/gmail.modify https://www.googleapis.com/auth/gmail.send';
const API='https://gmail.googleapis.com/gmail/v1/users/me';
let token=null,tokenClient=null,profile=null,currentLabel='INBOX',nextPageToken=null,selected=null,selectedThreadId=null,selectedMessage=null,searchQuery='',refreshing=false;
const labels=[['INBOX','Inbox','⌂'],['STARRED','Starred','★'],['SENT','Sent','➤'],['DRAFT','Drafts','▱'],['TRASH','Trash','♜']];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function setup(){document.body.innerHTML=`<main class="setup"><section class="setup-card"><h1>Set up AitherMail</h1><p>AitherMail is a static GitHub Pages app. It does not use Render, a backend, or a Gmail API key.</p><p>Google OAuth uses a public Web client ID to authorize Gmail access.</p><ol><li>Enable the Gmail API in Google Cloud.</li><li>Configure OAuth consent as External → Testing and add your Gmail address as a test user.</li><li>Create OAuth credentials → Web application.</li><li>Add <code>https://${location.hostname}</code> and <code>http://localhost:8000</code> as JavaScript origins.</li><li>Put the OAuth client ID in <code>app.js</code> as <code>CLIENT_ID</code>.</li></ol><p><b>No API key is required.</b> The Gmail access token exists only in memory.</p></section></main>`}
function signedOut(){document.body.innerHTML=`<main class="signedout"><section class="login-card"><div class="logo">Aither<span>Mail</span></div><p>Real Gmail, without the clutter.</p><button class="send" onclick="login()">Sign in with Google</button><p id="loginError" class="error hidden"></p></section></main>`}
function login(){if(!window.google?.accounts?.oauth2){setTimeout(login,300);return}if(!tokenClient)tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPES,callback:async r=>{if(r.error){showLoginError(r.error_description||r.error);return}token=r.access_token;try{profile=await api('/profile');renderApp();await loadMessages(true)}catch(e){token=null;showLoginError(e.message)}}});tokenClient.requestAccessToken({prompt:''})}
function showLoginError(x){const el=$('#loginError');if(el){el.textContent=x;el.classList.remove('hidden')}}
async function api(path,opts={},retry=true){if(!token)throw Error('Not signed in');const res=await fetch(API+path,{...opts,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(opts.headers||{})}});if(res.status===401&&retry){await new Promise((resolve,reject)=>tokenClient.requestAccessToken({prompt:'',callback:r=>r.error?reject(Error(r.error_description||r.error)):resolve()}));return api(path,opts,false)}if(!res.ok){let msg='Gmail API error '+res.status;try{const j=await res.json();msg=j.error?.message||msg}catch{}throw Error(msg)}return res.status===204?null:res.json()}
function renderApp(){document.body.innerHTML=`<div class="app"><aside class="rail"><div class="brand">Aither<span>Mail</span></div><button class="compose" onclick="openCompose()">Compose</button><nav class="folders">${labels.map(([id,name,ico])=>`<button class="folder ${id===currentLabel?'active':''}" onclick="switchFolder('${id}')"><span class="ico">${ico}</span><span>${name}</span><span class="count" id="count-${id}"></span></button>`).join('')}</nav><div class="account"><div class="avatar">${esc((profile.emailAddress||'?')[0].toUpperCase())}</div><div><b>${esc(profile.emailAddress)}</b><small>Gmail account</small></div><button class="signout" onclick="logout()" title="Sign out">↪</button></div></aside><section class="list"><div class="topbar"><form class="search" onsubmit="doSearch(event)"><span>⌕</span><input id="search" placeholder="Search Gmail" value="${esc(searchQuery)}" autocomplete="off"></form></div><div class="listhead"><span id="folderTitle">${labels.find(x=>x[0]===currentLabel)?.[1]||'Inbox'}</span><button class="iconbtn" onclick="loadMessages(true)" aria-label="Refresh">↻</button></div><div id="messages" class="messages"></div></section><section id="reader" class="reader"><div class="readerbar"><button class="back" onclick="closeReader()">←</button><button onclick="archiveSelected()">Archive</button><button onclick="trashSelected()">Trash</button><button onclick="toggleStarSelected()">★</button><button onclick="markUnreadSelected()">Mark unread</button><button class="iconbtn" style="margin-left:auto" onclick="closeReader()">×</button></div><div id="readerbody" class="readerbody"><div class="empty">Select a message to read it.</div></div></section></div>`}
async function switchFolder(id){currentLabel=id;selected=null;selectedThreadId=null;selectedMessage=null;searchQuery='';document.querySelectorAll('.folder').forEach((b,i)=>b.classList.toggle('active',labels[i][0]===id));$('#folderTitle').textContent=labels.find(x=>x[0]===id)[1];$('#search').value='';closeReader();await loadMessages(true)}
function skeleton(){return '<div class="loading">'+Array.from({length:7},()=>'<div class="skeleton"></div>').join('')+'</div>'}
async function loadMessages(reset=false){if(refreshing)return;refreshing=true;const box=$('#messages');if(!box){refreshing=false;return}if(reset){nextPageToken=null;box.innerHTML=skeleton()}else{$('.load-more')?.remove()}try{const q=new URLSearchParams({maxResults:'25'});if(currentLabel)q.set('labelIds',currentLabel);if(searchQuery)q.set('q',searchQuery);if(!reset&&nextPageToken)q.set('pageToken',nextPageToken);const page=await api('/messages?'+q);nextPageToken=page.nextPageToken||null;const msgs=await Promise.all((page.messages||[]).map(m=>api('/messages/'+m.id+'?format=metadata&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Subject&metadataHeaders=Date')));const html=msgs.map(messageRow).join('');if(reset)box.innerHTML=html||'<div class="empty">No messages here.</div>';else box.insertAdjacentHTML('beforeend',html);if(nextPageToken)box.insertAdjacentHTML('beforeend','<div class="load-more" style="padding:16px;text-align:center"><button class="secondary" onclick="loadMessages(false)">Load more</button></div>')}catch(e){box.innerHTML='<div class="empty">Could not load mail.<br><br>'+esc(e.message)+'</div>';toast(e.message)}finally{refreshing=false}}
function header(m,n){return(m.payload?.headers||[]).find(h=>h.name.toLowerCase()===n.toLowerCase())?.value||''}
function messageRow(m){const unread=(m.labelIds||[]).includes('UNREAD'),star=(m.labelIds||[]).includes('STARRED');const from=parseFrom(header(m,'From'));return `<div class="row ${unread?'unread':''} ${selected===m.id?'selected':''}" data-id="${esc(m.id)}" role="button" tabindex="0" onclick="openMessage('${esc(m.id)}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openMessage('${esc(m.id)}')}"><button class="star ${star?'on':''}" aria-label="${star?'Unstar':'Star'}" onclick="event.stopPropagation();toggleStar('${esc(m.id)}',${star})">★</button><div><div class="sender">${esc(from.name||from.email)}</div><div class="subject">${esc(header(m,'Subject')||'(no subject)')}</div><div class="snippet">${esc(m.snippet||'')}</div></div><span class="date">${formatDate(header(m,'Date'))}</span></div>`}
function parseFrom(v){const x=v.match(/^(.*?)[ ]*<([^>]+)>$/);return x?{name:x[1].replace(/^"|"$/g,''),email:x[2]}:{name:v,email:v}}
function formatDate(v){if(!v)return '';const d=new Date(v);return isNaN(d)?v.slice(0,16):d.toLocaleDateString(undefined,{month:'short',day:'numeric'})}
function b64decode(s){s=(s||'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bytes=Uint8Array.from(atob(s),c=>c.charCodeAt(0));return new TextDecoder('utf-8').decode(bytes)}
function findBody(part,want){if(!part)return null;if(part.mimeType===want&&part.body?.data)return b64decode(part.body.data);for(const p of part.parts||[]){const x=findBody(p,want);if(x!==null)return x}return null}
function plainToHtml(s){return esc(s).replace(/\r?\n/g,'<br>')}
async function openMessage(id){selected=id;document.querySelectorAll('.row').forEach(r=>r.classList.remove('selected'));document.querySelector(`[data-id="${CSS.escape(id)}"]`)?.classList.add('selected');try{const m=await api('/messages/'+id+'?format=full');selectedThreadId=m.threadId||null;selectedMessage=m;const from=parseFrom(header(m,'From'));const to=header(m,'To');const subject=header(m,'Subject')||'(no subject)';const html=findBody(m.payload,'text/html');const plain=findBody(m.payload,'text/plain');const body=html||plainToHtml(plain||m.snippet||'');$('#readerbody').innerHTML=`<h1>${esc(subject)}</h1><div class="meta"><div class="avatar">${esc((from.name||from.email||'?')[0].toUpperCase())}</div><div><strong>${esc(from.name||from.email)}</strong><span>${esc(from.email)} · to ${esc(to)}</span></div></div><iframe class="email-frame" sandbox="" title="Email content" srcdoc="${esc(body)}"></iframe><div style="margin-top:24px"><button class="send" onclick="openCompose(true)">Reply</button></div>`;$('#reader').classList.add('open');if((m.labelIds||[]).includes('UNREAD')){await api('/messages/'+id+'/modify',{method:'POST',body:JSON.stringify({removeLabelIds:['UNREAD']})});loadMessages(true)}}catch(e){toast(e.message)}}
async function action(id,endpoint,body){try{await api('/messages/'+id+endpoint,{method:'POST',body:body?JSON.stringify(body):undefined});await loadMessages(true);if(selected===id)closeReader()}catch(e){toast(e.message)}}
function archiveSelected(){if(selected)action(selected,'/modify',{removeLabelIds:['INBOX']})}
function trashSelected(){if(selected)action(selected,'/trash')}
function markUnreadSelected(){if(selected)action(selected,'/modify',{addLabelIds:['UNREAD']})}
function toggleStarSelected(){if(!selected)return;const star=selectedMessage?.labelIds?.includes('STARRED');action(selected,'/modify',{addLabelIds:star?[]:['STARRED'],removeLabelIds:star?['STARRED']:[]})}
function toggleStar(id,on){action(id,'/modify',{addLabelIds:on?[]:['STARRED'],removeLabelIds:on?['STARRED']:[]})}
function closeReader(){$('#reader')?.classList.remove('open');selected=null;selectedThreadId=null;selectedMessage=null}
function doSearch(e){e.preventDefault();searchQuery=$('#search').value.trim();loadMessages(true)}
function openCompose(reply=false){if(reply&&selected){api('/messages/'+selected+'?format=full').then(m=>{const from=parseFrom(header(m,'Reply-To')||header(m,'From'));const subject=/^re:/i.test(header(m,'Subject'))?header(m,'Subject'):'Re: '+(header(m,'Subject')||'');const mid=header(m,'Message-ID');const refs=header(m,'References');showCompose(from.email,subject,'',`<input id="replyMessageId" type="hidden" value="${esc(mid)}"><input id="replyReferences" type="hidden" value="${esc(refs)}">`)})}else showCompose('','','','')}
function showCompose(to,subject,body,extra){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="compose"><form class="composebox" onsubmit="sendMail(event)"><div class="modalhead"><span>${to?'Reply':'New message'}</span><button type="button" onclick="$('#compose').remove()">×</button></div><div class="fields"><input id="to" required placeholder="To" value="${esc(to)}"><input id="subject" placeholder="Subject" value="${esc(subject)}">${extra}<textarea id="body" placeholder="Write a message…">${esc(body)}</textarea></div><div class="modalfoot"><button type="button" class="secondary" onclick="$('#compose').remove()">Discard</button><button id="sendBtn" class="send">Send</button></div></form></div>`);setTimeout(()=>$('#to')?.focus(),50)}
function b64encode(s){const bytes=new TextEncoder().encode(s);let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function rfc2047(s){return/^[\x00-\x7F]*$/.test(s)?s:'=?UTF-8?B?'+b64encode(s)+'?='}
function rawMail(to,subject,body,mid,refs){const lines=['From: '+profile.emailAddress,'To: '+to,'Subject: '+rfc2047(subject||''),'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: 8bit'];if(mid)lines.push('In-Reply-To: '+mid);if(mid)lines.push('References: '+((refs?refs+' ':'')+mid).trim());return b64encode(lines.join('\r\n')+'\r\n\r\n'+body)}
async function sendMail(e){e.preventDefault();const btn=$('#sendBtn');btn.disabled=true;btn.textContent='Sending…';try{const mid=$('#replyMessageId')?.value||'';const refs=$('#replyReferences')?.value||'';const raw=rawMail($('#to').value.trim(),$('#subject').value,$('#body').value,mid,refs);const payload={raw};if(mid&&selectedThreadId)payload.threadId=selectedThreadId;await api('/messages/send',{method:'POST',body:JSON.stringify(payload)});$('#compose').remove();toast('Message sent');if(currentLabel==='SENT')loadMessages(true)}catch(err){toast(err.message);btn.disabled=false;btn.textContent='Send'}}
function toast(msg){const old=$('.toast');old?.remove();const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),4500)}
function logout(){if(token&&window.google?.accounts?.oauth2?.revoke){google.accounts.oauth2.revoke(token,()=>{token=null;profile=null;tokenClient=null;signedOut()})}else{token=null;profile=null;tokenClient=null;signedOut()}}
if(CLIENT_ID.startsWith('YOUR_'))setup();else signedOut();