const BACKEND_URL=(window.AITHER_BACKEND_URL||'https://aitherbackendnew.onrender.com').replace(/\/$/,'');
const MAIL_API=BACKEND_URL;
let aitherUser=null,messages=[],selected=null,search='',box='inbox',loading=false;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function token(){return localStorage.getItem('aither_session_token')||''}
function authHeaders(){const t=token();return t?{'Authorization':`Bearer ${t}`}:{}}
async function backend(path,opts={}){const r=await fetch(BACKEND_URL+path,{credentials:'include',...opts,headers:{'Content-Type':'application/json',...authHeaders(),...(opts.headers||{})}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(d.detail||`AitherBackend error ${r.status}`);return d}
async function session(){try{const d=await backend('/api/auth/session');if(d.authenticated){aitherUser=d.user;return true}}catch(e){}localStorage.removeItem('aither_session_token');return false}
function authScreen(){document.body.innerHTML=`<main class="signedout"><section class="login-card"><div class="logo">Aither<span>Mail</span></div><p>Your Aither email workspace.</p><div class="auth-tabs"><button id="loginTab" class="active" onclick="authMode('login')">Sign in</button><button id="registerTab" onclick="authMode('register')">Create account</button></div><form id="authForm" onsubmit="submitAuth(event)"></form><p id="authError" class="error hidden"></p></section></main>`;authMode('login')}
function authMode(mode){$('#loginTab').classList.toggle('active',mode==='login');$('#registerTab').classList.toggle('active',mode==='register');$('#authForm').innerHTML=mode==='register'?`<input id="authName" required maxlength="80" placeholder="Name"><input id="authEmail" required type="email" placeholder="Email"><input id="authPassword" required minlength="8" type="password" placeholder="Password"><button class="send full">Create Aither Account</button>`:`<input id="authEmail" required type="email" placeholder="Email"><input id="authPassword" required type="password" placeholder="Password"><button class="send full">Sign in</button>`}
async function submitAuth(e){e.preventDefault();const reg=!!$('#authName'),b=e.submitter;b.disabled=true;try{const body=reg?{name:$('#authName').value.trim(),email:$('#authEmail').value.trim(),password:$('#authPassword').value}:{email:$('#authEmail').value.trim(),password:$('#authPassword').value};const d=await backend(reg?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify(body)});if(d.session_token)localStorage.setItem('aither_session_token',d.session_token);aitherUser=d.user;renderApp();await refresh()}catch(x){const er=$('#authError');er.textContent=x.message;er.classList.remove('hidden');b.disabled=false}}
function renderApp(){document.body.innerHTML=`<div class="mailapp"><aside class="rail" id="rail"><div class="brand">Aither<span>Mail</span></div><div class="accountcard"><b>${esc(aitherUser?.name||'Aither User')}</b><small>${esc(aitherUser?.email||'')}</small></div><button class="compose" onclick="compose()">＋ Compose</button><nav><button class="folder active" data-box="inbox" onclick="setBox('inbox')">▣ <span>Inbox</span><b id="inboxCount"></b></button><button class="folder" data-box="sent" onclick="setBox('sent')">➤ <span>Sent</span></button><button class="folder" data-box="all" onclick="setBox('all')">✉ <span>All Mail</span></button></nav><div class="railbottom"><button onclick="showSettings()">⚙ Settings</button><button onclick="logout()">↪ Sign out</button></div></aside><main class="workspace"><header class="header"><button class="mobile" onclick="toggleRail()">☰</button><form class="search" onsubmit="doSearch(event)"><span>⌕</span><input id="search" placeholder="Search mail" autocomplete="off"><button type="submit">Search</button></form><button class="iconbtn" onclick="refresh()" title="Refresh">↻</button></header><section class="toolbar"><label><input id="selectAll" type="checkbox" onchange="selectAll(this.checked)"> Select all</label><button onclick="deleteSelected()">Delete</button><button onclick="refresh()">Refresh</button><span id="status"></span></section><section class="content"><div class="message-list" id="messageList"></div><article class="message-view" id="messageView"><div class="empty"><strong>Aither Mail</strong><span>Select an email to read it.</span></div></article></section></main></div>`;window.addEventListener('keydown',keyboardShortcuts)}
function toggleRail(){$('#rail')?.classList.toggle('open')}
async function setBox(v){box=v;selected=null;document.querySelectorAll('.folder').forEach(x=>x.classList.toggle('active',x.dataset.box===v));closeMessage();await refresh();closeRail()}
function closeRail(){if(innerWidth<=600)$('#rail')?.classList.remove('open')}
async function mail(path,opts={}){const r=await fetch(MAIL_API+path,{...opts,credentials:'include',headers:{'Content-Type':'application/json',...authHeaders(),...(opts.headers||{})}});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{}if(!r.ok)throw Error(data.detail||data.message||`Mail service returned ${r.status}`);return data}
function normalize(m){return{id:m.id||m.ID,from:m.from||m.sender||'',to:m.to||m.recipients||'',cc:m.cc||'',subject:m.subject||'(no subject)',date:m.date||m.created_at||'',text:m.text||m.body||'',html:m.html||'',read:Boolean(m.read),folder:m.folder||'inbox',raw:m}}
async function refresh(){if(loading)return;loading=true;setStatus('Refreshing…');try{const d=await mail(`/api/mail/messages?start=0&limit=100&folder=${encodeURIComponent(box)}`);messages=(d.items||[]).map(normalize);$('#inboxCount').textContent=box==='inbox'?(messages.length||''):'';renderList();setStatus(`${messages.length} message${messages.length===1?'':'s'}`)}catch(e){setStatus('Offline');renderListError(e)}finally{loading=false}}
function filtered(){let a=[...messages];if(search){const q=search.toLowerCase();a=a.filter(m=>(m.from+' '+m.to+' '+m.cc+' '+m.subject+' '+strip(m.text)).toLowerCase().includes(q))}return a.sort((a,b)=>new Date(b.date)-new Date(a.date))}
function renderList(){const list=$('#messageList');if(!list)return;const a=filtered();$('#selectAll').checked=false;if(!a.length){list.innerHTML='<div class="empty"><strong>No messages</strong><span>'+ (search?'No messages match your search.':box==='sent'?'No sent messages yet.':'Your inbox is empty.')+'</span>'+ (search?'<button class="secondary" onclick="clearSearch()">Clear search</button>':'')+'</div>';return}list.innerHTML=a.map(m=>`<button class="mailrow ${selected===m.id?'selected':''}" data-id="${esc(m.id)}" onclick="openMessage('${esc(m.id)}')"><input type="checkbox" onclick="event.stopPropagation()" data-select="${esc(m.id)}"><div class="avatar">${esc((displaySender(box==='sent'?m.to:m.from)||'?')[0].toUpperCase())}</div><div class="rowcopy"><b>${esc(displaySender(box==='sent'?m.to:m.from)||'Unknown')}</b><strong>${esc(m.subject)}</strong><span>${esc(strip(m.text).slice(0,140))}</span></div><time>${date(m.date)}</time></button>`).join('');list.querySelectorAll('[data-select]').forEach(x=>x.addEventListener('change',updateSelected))}
function renderListError(e){$('#messageList').innerHTML=`<div class="empty"><strong>Could not load mail</strong><span>${esc(e.message)}</span><button class="secondary" onclick="refresh()">Try again</button></div>`}
async function openMessage(id){selected=id;renderList();const local=messages.find(x=>x.id===id);if(!local)return;let m=local;try{m=normalize(await mail('/api/mail/messages/'+encodeURIComponent(id)))}catch(e){}const body=m.html?extractBody(m.html):escapeText(m.text);$('#messageView').classList.add('open');$('#messageView').innerHTML=`<div class="viewhead"><button class="mobile" onclick="closeMessage()">←</button><div class="subjectwrap"><h1>${esc(m.subject)}</h1><p>${esc(displaySender(m.from))} → ${esc(m.to)}</p><small>${esc(m.date)}</small></div><div class="viewactions"><button onclick="deleteMessage('${esc(m.id)}')">Delete</button><button onclick="compose('${esc(m.from)}','Re: ${esc(m.subject)}',${JSON.stringify(replyBody(m))})">Reply</button></div></div><div class="emailbody"><iframe sandbox class="email-frame" title="Email content"></iframe></div><details class="source"><summary>View raw message</summary><pre>${esc(JSON.stringify(m.raw,null,2))}</pre></details>`;const frame=$('#messageView iframe');frame.srcdoc=body;frame.onload=()=>{try{const h=Math.min(900,Math.max(350,frame.contentDocument.body.scrollHeight+30));frame.style.height=h+'px'}catch(e){}}}
function closeMessage(){$('#messageView')?.classList.remove('open');if($('#messageView'))$('#messageView').innerHTML='<div class="empty"><strong>Aither Mail</strong><span>Select an email to read it.</span></div>';selected=null;renderList()}
async function deleteMessage(id){try{await mail('/api/mail/messages/'+encodeURIComponent(id),{method:'DELETE'});toast('Message deleted');closeMessage();await refresh()}catch(e){toast(e.message)}}
async function deleteSelected(){const ids=[...document.querySelectorAll('[data-select]:checked')].map(x=>x.dataset.select);if(!ids.length){toast('Select messages first');return}if(!confirm(`Delete ${ids.length} message${ids.length===1?'':'s'}?`))return;try{await Promise.all(ids.map(id=>mail('/api/mail/messages/'+encodeURIComponent(id),{method:'DELETE'})));toast(`${ids.length} message${ids.length===1?'':'s'} deleted`);selected=null;await refresh()}catch(e){toast(e.message);await refresh()}}
function updateSelected(){const checks=[...document.querySelectorAll('[data-select]')],n=checks.filter(x=>x.checked).length;$('#selectAll').checked=checks.length>0&&n===checks.length;setStatus(n?`${n} selected`:`${messages.length} messages`)}
function selectAll(on){document.querySelectorAll('[data-select]').forEach(x=>x.checked=on);updateSelected()}
function compose(to='',subject='',body=''){const draft=JSON.parse(localStorage.getItem('aitherMailDraft')||'{}');const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<section class="composebox"><header><span>New message</span><button onclick="closeCompose(this)">×</button></header><div class="composefields"><input id="cto" placeholder="To" value="${esc(to||draft.to||'')}"><input id="cc" placeholder="Cc (optional)" value="${esc(draft.cc||'')}"><input id="cbcc" placeholder="Bcc (optional)" value="${esc(draft.bcc||'')}"><input id="csubject" placeholder="Subject" value="${esc(subject||draft.subject||'')}"></div><textarea id="cbody" placeholder="Write your message…">${esc(body||draft.body||'')}</textarea><footer><span id="draftStatus">Draft saved locally</span><button class="send" onclick="sendMessage(this)">Send</button></footer></section></div>`;document.body.appendChild(modal);['cto','cc','cbcc','csubject','cbody'].forEach(id=>$('#'+id).addEventListener('input',saveDraft));$('#cbody').focus();saveDraft()}
function saveDraft(){const data={to:$('#cto')?.value||'',cc:$('#cc')?.value||'',bcc:$('#cbcc')?.value||'',subject:$('#csubject')?.value||'',body:$('#cbody')?.value||''};localStorage.setItem('aitherMailDraft',JSON.stringify(data));const s=$('#draftStatus');if(s)s.textContent='Draft saved locally'}
function closeCompose(btn){localStorage.removeItem('aitherMailDraft');btn.closest('.modal')?.remove()}
async function sendMessage(btn){btn.disabled=true;const to=$('#cto').value.trim(),cc=$('#cc').value.trim(),bcc=$('#cbcc').value.trim(),subject=$('#csubject').value.trim(),body=$('#cbody').value;if(!to){toast('Add a recipient');btn.disabled=false;return}try{await mail('/api/mail/send',{method:'POST',body:JSON.stringify({to,cc,bcc,subject,body})});localStorage.removeItem('aitherMailDraft');btn.closest('.modal').remove();toast('Message sent');await refresh()}catch(e){toast('Send failed: '+e.message);btn.disabled=false}}
function replyBody(m){return `\n\n--- Original message ---\nFrom: ${m.from}\nDate: ${m.date}\nSubject: ${m.subject}\n\n${strip(m.text)}`}
function extractBody(v){const s=String(v);const i=s.indexOf('\r\n\r\n');return i>=0?s.slice(i+4):s.replace(/^[\s\S]*?<body[^>]*>/i,'').replace(/<\/body>[\s\S]*$/i,'')}
function escapeText(v){return esc(v).replace(/\r?\n/g,'<br>')}
function strip(v){return String(v||'').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function displaySender(v){const m=String(v||'').match(/^(.*?)\s*<([^>]+)>$/);return m?(m[1].replace(/^"|"$/g,'')||m[2]):v}
function date(v){const d=new Date(v);if(isNaN(d))return String(v||'').slice(0,18);const now=new Date();return d.toDateString()===now.toDateString()?d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):d.toLocaleDateString(undefined,{month:'short',day:'numeric'})}
function doSearch(e){e.preventDefault();search=$('#search').value.trim();renderList()}
function clearSearch(){search='';$('#search').value='';renderList()}
function setStatus(v){const x=$('#status');if(x)x.textContent=v}
function toast(v){const old=document.querySelector('.toast');if(old)old.remove();const x=document.createElement('div');x.className='toast';x.textContent=v;document.body.appendChild(x);setTimeout(()=>x.remove(),3200)}
function showSettings(){window.AitherMailSettings?.open?.()||toast(`Signed in as ${aitherUser?.email||'Aither Account'}`)}
function keyboardShortcuts(e){if(e.key==='Escape'){document.querySelector('.modal')?.remove();closeMessage();return}if(e.key==='/'&&!/input|textarea/i.test(document.activeElement.tagName)){e.preventDefault();$('#search')?.focus()}if(e.key==='c'&&!e.metaKey&&!e.ctrlKey&&!/input|textarea/i.test(document.activeElement.tagName))compose()}
async function logout(){try{await backend('/api/auth/logout',{method:'POST'})}catch(e){}localStorage.removeItem('aither_session_token');location.reload()}
async function boot(){if(await session()){renderApp();await refresh();setInterval(refresh,5000)}else authScreen()}
boot();