(()=>{
  const API='https://gmail.googleapis.com/gmail/v1/users/me';
  const state={messages:[],pageToken:'',cache:new Map(),loading:false};
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const strip=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
  const fmtDate=d=>{const x=new Date(d);if(Number.isNaN(x.getTime()))return '';const now=new Date();return x.toDateString()===now.toDateString()?x.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):x.toLocaleDateString([], {month:'short',day:'numeric',year:x.getFullYear()===now.getFullYear()?undefined:'numeric'});};
  function headers(){return window.AitherGmail?.authHeaders?.()||null}
  async function gmail(path,opts={}){
    const h=headers();if(!h)throw Error('Connect your Gmail account first.');
    const r=await fetch(API+path,{...opts,headers:{Authorization:h.Authorization,'Content-Type':'application/json',...(opts.headers||{})}});
    const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(d.error?.message||`Gmail error ${r.status}`);return d;
  }
  function dec(s){try{let x=String(s||'').replace(/-/g,'+').replace(/_/g,'/');while(x.length%4)x+='=';return decodeURIComponent(escape(atob(x)))}catch{return ''}}
  function partBody(p){if(!p)return '';if(p.body?.data)return dec(p.body.data);for(const c of (p.parts||[])){const v=partBody(c);if(v)return v}return ''}
  function findPart(p,mime){if(!p)return null;if(p.mimeType===mime&&p.body?.data)return p;for(const c of (p.parts||[])){const v=findPart(c,mime);if(v)return v}return null}
  function header(m,n){return (m.payload?.headers||[]).find(x=>String(x.name).toLowerCase()===n.toLowerCase())?.value||''}
  function normalize(m,full=false){const labels=m.labelIds||[];if(!full)return {id:m.id,threadId:m.threadId,from:m.from||'',to:m.to||'',subject:m.subject||'(no subject)',date:m.date||new Date(Number(m.internalDate||Date.now())).toISOString(),text:'',html:'',read:!labels.includes('UNREAD'),labels,snippet:m.snippet||'',raw:m};const payload=m.payload||{};const html=partBody(findPart(payload,'text/html'));const plain=partBody(findPart(payload,'text/plain'))||(!html?partBody(payload):'');return {id:m.id,threadId:m.threadId,from:header(m,'From'),to:header(m,'To'),cc:header(m,'Cc'),subject:header(m,'Subject')||'(no subject)',date:header(m,'Date')||new Date(Number(m.internalDate||Date.now())).toISOString(),text:plain,html,read:!labels.includes('UNREAD'),labels,snippet:m.snippet||strip(plain).slice(0,180),raw:m};}
  async function ensure(){if(!window.AitherGmail?.connect)throw Error('Gmail connection is still loading.');await window.AitherGmail.connect();}
  async function refreshGmail(){if(state.loading)return;state.loading=true;try{await ensure();const box=window.box||'inbox';const label=box==='sent'?'SENT':box==='trash'?'TRASH':box==='all'?null:'INBOX';let q=window.search||'';let path=`/messages?maxResults=100${label?`&labelIds=${label}`:''}${q?`&q=${encodeURIComponent(q)}`:''}`;const d=await gmail(path);state.pageToken=d.nextPageToken||'';state.messages=(d.messages||[]).map(m=>{const old=state.cache.get(m.id);const next=normalize({...m,...(old?.read!==undefined?{labelIds:old.labels}:{} )});state.cache.set(m.id,next);return next});window.messages=state.messages;window.selected=null;window.renderList?.();const count=$('#inboxCount');if(count)count.textContent=box==='inbox'?(state.messages.filter(m=>!m.read).length||''):'';window.setStatus?.(`${state.messages.length}${state.pageToken?'+' :''} message${state.messages.length===1?'':'s'}`)}catch(e){window.renderListError?.(e)}finally{state.loading=false}}
  window.loadMoreGmail=async()=>{if(!state.pageToken||state.loading)return;state.loading=true;try{await ensure();const box=window.box||'inbox';const label=box==='sent'?'SENT':box==='trash'?'TRASH':box==='all'?null:'INBOX';const q=window.search||'';const d=await gmail(`/messages?maxResults=100&pageToken=${encodeURIComponent(state.pageToken)}${label?`&labelIds=${label}`:''}${q?`&q=${encodeURIComponent(q)}`:''}`);state.pageToken=d.nextPageToken||'';for(const item of (d.messages||[])){if(!state.messages.some(m=>m.id===item.id)){const old=state.cache.get(item.id);const m=old||normalize(item);state.cache.set(item.id,m);state.messages.push(m)}}window.messages=state.messages;window.renderList?.();window.setStatus?.(`${state.messages.length}${state.pageToken?'+':''} messages`)}catch(e){window.toast?.(e.message)}finally{state.loading=false}};
  async function openGmail(id){let m=state.cache.get(id);try{m=normalize(await gmail('/messages/'+encodeURIComponent(id)+'?format=full'),true);state.cache.set(id,m);const unread=!m.read;if(unread)await gmail('/messages/'+encodeURIComponent(id)+'/modify',{method:'POST',body:JSON.stringify({removeLabelIds:['UNREAD']})});if(unread)m.read=true;const i=state.messages.findIndex(x=>x.id===id);if(i>=0)state.messages[i]=m;window.messages=state.messages;window.selected=id;window.renderList?.();const view=$('#messageView');if(!view)return;const body=m.html||('<pre style="white-space:pre-wrap;font:inherit">'+esc(m.text)+'</pre>');view.classList.add('open');view.innerHTML=`<div class="viewhead"><button class="mobile" onclick="closeMessage()">${window.icon?.('back')||''}</button><div class="subjectwrap"><h1>${esc(m.subject)}</h1><p>${esc(m.from)} → ${esc(m.to)}</p><small>${esc(fmtDate(m.date))}</small></div><div class="viewactions"><button title="Delete" onclick="gmailTrash('${esc(id)}')">${window.icon?.('trash')||''}</button><button title="Reply" onclick="compose(${JSON.stringify(m.from)},${JSON.stringify('Re: '+m.subject)},${JSON.stringify(m.text)})">${window.icon?.('reply')||''}</button></div></div><div class="emailbody"><iframe sandbox="allow-popups" class="email-frame" title="Email content"></iframe></div>`;const frame=view.querySelector('iframe');frame.srcdoc=body;frame.onload=()=>{try{frame.style.height=Math.min(1200,Math.max(350,frame.contentDocument.body.scrollHeight+40))+'px'}catch{}}}catch(e){window.toast?.(e.message)}}
  window.gmailTrash=async id=>{try{await gmail('/messages/'+encodeURIComponent(id)+'/trash',{method:'POST'});state.cache.delete(id);window.closeMessage?.();await refreshGmail()}catch(e){window.toast?.(e.message)}};
  window.gmailMarkUnread=async id=>{try{await gmail('/messages/'+encodeURIComponent(id)+'/modify',{method:'POST',body:JSON.stringify({addLabelIds:['UNREAD']})});const m=state.cache.get(id);if(m)m.read=false;window.renderList?.();window.toast?.('Marked unread')}catch(e){window.toast?.(e.message)}};
  window.gmailMarkRead=async id=>{try{await gmail('/messages/'+encodeURIComponent(id)+'/modify',{method:'POST',body:JSON.stringify({removeLabelIds:['UNREAD']})});const m=state.cache.get(id);if(m)m.read=true;window.renderList?.();window.toast?.('Marked read')}catch(e){window.toast?.(e.message)}};
  window.refresh=refreshGmail;window.openMessage=openGmail;
  window.addEventListener('aither:gmail-connected',refreshGmail);
  document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>refreshGmail(),250));
})();