package main

import("bytes";"encoding/json";"fmt";"io";"log";"net/http";"net/smtp";"os";"strings")
const backend="https://aitherbackend.onrender.com"
func auth(r *http.Request)(string,bool){req,_:=http.NewRequest("GET",backend+"/api/auth/session",nil);if v:=r.Header.Get("Authorization");v!=""{req.Header.Set("Authorization",v)};if v:=r.Header.Get("Cookie");v!=""{req.Header.Set("Cookie",v)};resp,e:=http.DefaultClient.Do(req);if e!=nil||resp.StatusCode<200||resp.StatusCode>=300{return "",false};defer resp.Body.Close();var d struct{Authenticated bool `json:"authenticated"`;User struct{Email string `json:"email"`} `json:"user"`};if json.NewDecoder(resp.Body).Decode(&d)!=nil{return "",false};return d.User.Email,d.Authenticated||d.User.Email!=""}
func main(){port:=os.Getenv("PORT");if port==""{port="8080"};http.HandleFunc("/api/health",func(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","application/json");w.Write([]byte(`{"ok":true,"service":"AitherMail"}`))});http.HandleFunc("/api/v1/send",send);http.HandleFunc("/api/v2/messages",messages);http.HandleFunc("/api/v1/messages/",message);http.HandleFunc("/",static);log.Printf("AitherMail listening on :%s",port);log.Fatal(http.ListenAndServe(":"+port,nil))}
func proxy(w http.ResponseWriter,r *http.Request,method,path string){email,ok:=auth(r);if !ok{http.Error(w,"unauthorized",401);return};req:=must(method,"http://127.0.0.1:8025"+path,r);resp,e:=http.DefaultClient.Do(req);if e!=nil{http.Error(w,e.Error(),502);return};defer resp.Body.Close();b,_:=io.ReadAll(resp.Body);if path=="/api/v2/messages"{b=filter(b,email)};if ct:=resp.Header.Get("Content-Type");ct!=""{w.Header().Set("Content-Type",ct)}else{w.Header().Set("Content-Type","application/json")};w.WriteHeader(resp.StatusCode);w.Write(b)}
func must(m,u string,r *http.Request)*http.Request{x,_:=http.NewRequest(m,u,r.Body);if v:=r.Header.Get("Authorization");v!=""{x.Header.Set("Authorization",v)};return x}
func filter(b []byte,email string)[]byte{var d struct{Total int `json:"total"`;Count int `json:"count"`;Start int `json:"start"`;Items []json.RawMessage `json:"items"`};if json.Unmarshal(b,&d)!=nil{return b};out:=d.Items[:0];for _,raw:=range d.Items{var m struct{Content struct{Headers map[string][]string `json:"Headers"`} `json:"Content"`};if json.Unmarshal(raw,&m)==nil{ok:=false;for _,k:=range []string{"From","To","Cc","Bcc"}{for _,v:=range m.Content.Headers[k]{if strings.Contains(strings.ToLower(v),strings.ToLower(email)){ok=true}}};if ok{out=append(out,raw)}}};d.Items=out;d.Count=len(out);d.Total=len(out);x,_:=json.Marshal(d);return x}
func messages(w http.ResponseWriter,r *http.Request){proxy(w,r,"GET",r.URL.RequestURI())}
func message(w http.ResponseWriter,r *http.Request){email,ok:=auth(r);if !ok{http.Error(w,"unauthorized",401);return};id:=strings.TrimPrefix(r.URL.Path,"/api/v1/messages/");if r.Method=="DELETE"{req,_:=http.NewRequest("GET","http://127.0.0.1:8025/api/v1/messages/"+id,nil);resp,e:=http.DefaultClient.Do(req);if e!=nil||resp.StatusCode!=200{http.Error(w,"message not found",404);return};defer resp.Body.Close();b,_:=io.ReadAll(resp.Body);if !bytes.Contains(bytes.ToLower(b),[]byte(strings.ToLower(email))){http.Error(w,"forbidden",403);return}};proxy(w,r,r.Method,"/api/v1/messages/"+id)}
func send(w http.ResponseWriter,r *http.Request){email,ok:=auth(r);if !ok{http.Error(w,"unauthorized",401);return};var d struct{From,To,Cc,Bcc,Subject,Body string};if json.NewDecoder(r.Body).Decode(&d)!=nil{http.Error(w,"invalid json",400);return};if d.To==""{http.Error(w,"recipient required",400);return};d.From=email;headers:=fmt.Sprintf("From: %s\r\nTo: %s\r\n",d.From,d.To);if d.Cc!=""{headers+="Cc: "+d.Cc+"\r\n"};if d.Bcc!=""{headers+="Bcc: "+d.Bcc+"\r\n"};headers+=fmt.Sprintf("Subject: %s\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n%s\r\n",d.Subject,d.Body);to:=append(strings.Split(d.To,","),strings.Split(d.Cc,",")...);to=append(to,strings.Split(d.Bcc,",")...);var rcpt []string;for _,x:=range to{if s:=strings.TrimSpace(x);s!=""{rcpt=append(rcpt,s)}};if e:=smtp.SendMail("127.0.0.1:1025",nil,d.From,rcpt,[]byte(headers));e!=nil{http.Error(w,e.Error(),502);return};w.Header().Set("Content-Type","application/json");w.Write([]byte(`{"ok":true,"message":"sent"}`))}
func static(w http.ResponseWriter,r *http.Request){p:=r.URL.Path;if p=="/"{p="/index.html"};f:=strings.TrimPrefix(p,"/");http.ServeFile(w,r,"/app/"+f)}
